"""add consultations diagnoses prescriptions with audit trail

Revision ID: 299e2b4587af
Revises: 783011e74656
Create Date: 2026-04-27 08:42:08.095940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299e2b4587af'
down_revision: Union[str, Sequence[str], None] = '783011e74656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
