"""add audit trail to prescriptions

Revision ID: 2eef983cd37a
Revises: c6a026298818
Create Date: 2026-05-01 08:01:03.264974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eef983cd37a'
down_revision: Union[str, Sequence[str], None] = 'c6a026298818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('prescriptions', sa.Column('superseded_at', sa.DateTime(), nullable=True))
    op.add_column('prescriptions', sa.Column('superseded_by_id', sa.Integer(), nullable=True))
    op.add_column('prescriptions', sa.Column('original_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prescriptions', 'prescriptions', ['original_id'], ['id'])
    op.create_foreign_key(None, 'prescriptions', 'users', ['superseded_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_column('prescriptions', 'original_id')
    op.drop_column('prescriptions', 'superseded_by_id')
    op.drop_column('prescriptions', 'superseded_at')
    op.drop_column('prescriptions', 'is_active')
    # ### end Alembic commands ###
