"""add check constraints to patients and users

Revision ID: 4a9ff236b5fc
Revises: 3cc7761c7c48
Create Date: 2026-04-23 10:55:33.527568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a9ff236b5fc'
down_revision: Union[str, Sequence[str], None] = '3cc7761c7c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
