"""add audit trail fields to diagnoses and prescriptions

Revision ID: 783011e74656
Revises: aeb920bdd238
Create Date: 2026-04-27 08:37:53.027486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783011e74656'
down_revision: Union[str, Sequence[str], None] = 'aeb920bdd238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('diagnoses', sa.Column('superseded_at', sa.DateTime(), nullable=True))
    op.add_column('diagnoses', sa.Column('superseded_by_id', sa.Integer(), nullable=True))
    op.add_column('diagnoses', sa.Column('original_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'diagnoses', 'users', ['superseded_by_id'], ['id'])
    op.create_foreign_key(None, 'diagnoses', 'diagnoses', ['original_id'], ['id'])
    op.add_column('prescriptions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('prescriptions', sa.Column('superseded_at', sa.DateTime(), nullable=True))
    op.add_column('prescriptions', sa.Column('superseded_by_id', sa.Integer(), nullable=True))
    op.add_column('prescriptions', sa.Column('original_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prescriptions', 'prescriptions', ['original_id'], ['id'])
    op.create_foreign_key(None, 'prescriptions', 'users', ['superseded_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_column('prescriptions', 'original_id')
    op.drop_column('prescriptions', 'superseded_by_id')
    op.drop_column('prescriptions', 'superseded_at')
    op.drop_column('prescriptions', 'is_active')
    op.drop_constraint(None, 'diagnoses', type_='foreignkey')
    op.drop_constraint(None, 'diagnoses', type_='foreignkey')
    op.drop_column('diagnoses', 'original_id')
    op.drop_column('diagnoses', 'superseded_by_id')
    op.drop_column('diagnoses', 'superseded_at')
    op.drop_column('diagnoses', 'is_active')
    # ### end Alembic commands ###
