"""add severity to drugs

Revision ID: a1fe38653550
Revises: a06c3c1fd1a2
Create Date: 2026-04-25 11:15:21.934490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1fe38653550'
down_revision: Union[str, Sequence[str], None] = 'a06c3c1fd1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugs', sa.Column('severity', sa.String(), nullable=False, server_default='Low'))
    op.alter_column('drugs', 'severity', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drugs', 'severity')
    # ### end Alembic commands ###
