"""add triage_records table

Revision ID: b333e771c8d2
Revises: b0e4a6f3c4a6
Create Date: 2026-05-20 09:37:51.896613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b333e771c8d2'
down_revision: Union[str, Sequence[str], None] = 'b0e4a6f3c4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('complaint', sa.Text(), nullable=False),
    sa.Column('mts_category', sa.String(length=50), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vitals', sa.JSON(), nullable=False),
    sa.Column('ai_recommended_color', sa.Enum('red', 'orange', 'yellow', 'green', 'blue', name='triagecolor'), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_rationale', sa.Text(), nullable=True),
    sa.Column('discriminators', sa.JSON(), nullable=False),
    sa.Column('final_color', sa.Enum('red', 'orange', 'yellow', 'green', 'blue', name='triagecolor'), nullable=False),
    sa.Column('nurse_override', sa.Boolean(), nullable=False),
    sa.Column('nurse_override_reason', sa.Text(), nullable=True),
    sa.Column('destination', sa.String(length=50), nullable=False),
    sa.Column('census_patient_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['nurse_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_records_id'), 'triage_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_records_id'), table_name='triage_records')
    op.drop_table('triage_records')
    # ### end Alembic commands ###
