"""add completed_by_id to checklist_items

Revision ID: b6b9c614bd18
Revises: 8e1dad46652c
Create Date: 2026-04-25 08:09:58.143990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6b9c614bd18'
down_revision: Union[str, Sequence[str], None] = '8e1dad46652c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist_items', sa.Column('completed_by_id', sa.Integer(), nullable=True))
    op.alter_column('checklist_items', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'checklist_items', 'users', ['completed_by_id'], ['id'])
    op.alter_column('surgical_checklists', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surgical_checklists', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'checklist_items', type_='foreignkey')
    op.alter_column('checklist_items', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('checklist_items', 'completed_by_id')
    # ### end Alembic commands ###
