"""remove severity from drugs

Revision ID: c6a026298818
Revises: b11d79a844b2
Create Date: 2026-04-30 13:04:26.708604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a026298818'
down_revision: Union[str, Sequence[str], None] = 'b11d79a844b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drugs', 'severity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugs', sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
